# `ref` specifies the commit, tag, or branch to be built
# The Ruby version of the package will be determined during the build process from `version.h`
# If `package-suffix` is empty, the package will be named `ruby-shopify-$RUBY_VERSION`, where version is `x.x.x`;
# if `package-suffix` is non-empty, the package will be named `ruby-shopify-$RUBY_VERSION-$SUFFIX`.
# In general, `package-suffix` should be empty for Ruby builds to be used in production, but it can be used
# to differentiate testing/beta builds or for builds with specialized patches.
# `package-version` must be incremented with each build of a given Ruby version (for any given suffix),
# ie. a first iteration of `ruby-shopify-2.3.1-foo` should have package version 1,
# a subsequent tweaked build should have package version 2, ...
# `memo` can be used to specify a brief description of the package, and will appear in the package description
# and changelog (alongside the `ref` and date/time)

ref: 0e64dc7b81d2a9c470a6c1bd2c3e327b5bb2ae96
package-suffix: ""
package-version: 1
memo: Production-ready standalone Ruby 2.3.1
