# A safeguard for accidentally opening a PR against upstream Github repo.
name: Pull Request
on: [pull_request]
jobs:
  check_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check if branch is microjit
        run: |
          if [ "$BASE_REF" != microjit ]; then
            echo "Only the microjit branch accepts pull requests, but it's '$BASE_REF'."
            exit 1
          fi
        env:
          BASE_REF: ${{ github.base_ref }}
