name: MMTK
on:
  push:
    paths-ignore:
      - 'doc/**'
      - '**/man/*'
      - '**.md'
      - '**.rdoc'
      - '**/.document'
      - '.*.yml'
  pull_request:
    # Do not use paths-ignore for required status checks
    # https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/collaborating-on-repositories-with-code-quality-features/troubleshooting-required-status-checks#handling-skipped-but-required-checks
  merge_group:

concurrency:
  group: ${{ github.workflow }} / ${{ startsWith(github.event_name, 'pull') && github.ref_name || github.sha }}
  cancel-in-progress: ${{ startsWith(github.event_name, 'pull') }}

permissions:
  contents: read

jobs:
  make:
    strategy:
      matrix:
        include:
          - test_task: test-all
      fail-fast: false

    env:
      GITPULLOPTIONS: --no-tags origin ${{ github.ref }}
      RUBY_DEBUG: ci

    runs-on: ${{ matrix.os || 'ubuntu-22.04' }}

    if: >-
      ${{!(false
      || contains(github.event.head_commit.message, '[DOC]')
      || contains(github.event.head_commit.message, 'Document')
      || contains(github.event.pull_request.title, '[DOC]')
      || contains(github.event.pull_request.title, 'Document')
      || contains(github.event.pull_request.labels.*.name, 'Document')
      || (github.event_name == 'push' && github.actor == 'dependabot[bot]')
      )}}

    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
        with:
          sparse-checkout-cone-mode: false
          sparse-checkout: /.github

      - uses: ./.github/actions/setup/ubuntu
        with:
          arch: ${{ matrix.arch }}

      - uses: ruby/setup-ruby@78c01b705fd9d5ad960d432d3a0cfa341d50e410 # v1.179.1
        with:
          ruby-version: '3.0'
          bundler: none

      - uses: ./.github/actions/setup/directories
        with:
          srcdir: src
          builddir: build
          makeup: true
          clean: true
          dummy-files: ${{ matrix.test_task == 'check' }}
          # Set fetch-depth: 10 so that Launchable can receive commits information.
          fetch-depth: 10

      - uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Clone and build MMTK
        run: >-
          git clone https://github.com/mmtk/mmtk-ruby &&
          cd mmtk-ruby/mmtk &&
          cargo build --release

      - name: Run configure
        env:
          arch: ${{ matrix.arch }}
          configure: ${{ matrix.configure }}
        run: >-
          $SETARCH ../src/configure -C --disable-install-doc ${configure:-cppflags=-DRUBY_DEBUG}
          ${arch:+--target=$arch-$OSTYPE --host=$arch-$OSTYPE}
          --with-mmtk-ruby=./mmtk-ruby

      - run: $SETARCH make prepare-gems
        if: ${{ matrix.test_task == 'test-bundled-gems' }}

      - run: $SETARCH make

      - name: make ${{ matrix.test_task }} RUN_OPTS="$RUN_OPTS"
        run: >-
          $SETARCH make -s ${{ matrix.test_task }}
          ${{ !contains(matrix.test_task, 'bundle') && 'RUBYOPT=-w' || '' }}
        timeout-minutes: 40
        env:
          RUBY_TESTOPTS: '-q --tty=no'
          TEST_BUNDLED_GEMS_ALLOW_FAILURES: ''
          PRECHECK_BUNDLED_GEMS: 'no'
          RUN_OPTS: '--mmtk --mmtk-plan=StickyImmix'

      - name: Clean build directory
        run: rm -rf $builddir/mmtk-ruby

  result:
    if: ${{ always() }}
    name: ${{ github.workflow }} result
    runs-on: ubuntu-latest
    needs: [make]
    steps:
      - run: exit 1
        working-directory:
        if: ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }}

defaults:
  run:
    working-directory: build
